version: "3.7"
services:
  netdata:
    image: d34dc3n73r/netdata-glibc
    container_name: netdata
    networks:
      - infrastructure_local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netdata.entrypoints=http"
      - "traefik.http.routers.netdata.rule=Host(${NETDATA_HOSTNAMES})"
      - "traefik.http.routers.netdata.middlewares=https-redirect@file"
      - "traefik.http.routers.netdata-secure.entrypoints=https"
      - "traefik.http.routers.netdata-secure.rule=Host(${NETDATA_HOSTNAMES})"
      - "traefik.http.routers.netdata-secure.tls=true"
      - "traefik.http.routers.netdata-secure.tls.certresolver=http"
      - "traefik.http.routers.netdata-secure.service=netdata"
      - "traefik.http.services.netdata.loadbalancer.server.port=${NETDATA_PORT}"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    environment:
      - PUID=${PUID}
      - PGID=${DOCKERGID}
      - TZ=${TIMEZONE}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /usr/bin/nvidia-smi:/usr/bin/nvidia-smi
      - /var/run/docker.sock:/var/run/docker.sock:ro

  portainer:
    image: portainer/portainer
    container_name: portainer
    networks:
      - infrastructure_local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.http.routers.portainer.rule=Host(${PORTAINER_HOSTNAMES})"
      - "traefik.http.routers.portainer.middlewares=https-redirect@file"
      - "traefik.http.routers.portainer-secure.entrypoints=https"
      - "traefik.http.routers.portainer-secure.rule=Host(${PORTAINER_HOSTNAMES})"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.tls.certresolver=http"
      - "traefik.http.routers.portainer-secure.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=${PORTAINER_PORT}"
    volumes:
      - portainerdata:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    
  # grafana:

  # prometheus:

  # cadvisor:

  # redis:

volumes:
  portainerdata:

networks:
  infrastructure_local:
    external: true