version: "3.7"
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    labels:
      - traefik.enable=true
      - traefik.port=${NETDATA_PORT}
      - traefik.frontend.rule=Host:${NETDATA_HOSTNAME}
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    environment:
      - PUID=${PUID}
      - PGID=${DOCKERGID}
      - TZ=${TIMEZONE}
    networks:
      - infrastructure_default
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw

  portainer:
    image: portainer/portainer
    container_name: portainer
    labels:
      - traefik.enable=true
      - traefik.port=${PORTAINER_PORT}
      - traefik.frontend.rule=Host:${PORTAINER_HOSTNAME}
    networks:
      - infrastructure_default
    volumes:
      - data_portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    
  # grafana:

  # prometheus:

  # cadvisor:

  # redis:

volumes:
  data_portainer:
networks:
  infrastructure_default:
    external: true
