[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[log]

[api]
  dashboard = true
  insecure = true

[ping]
  entryPoint = "traefik"

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false