api:
  dashboard: true
  
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  smtp:
    address: ":25"
  mysql:
    address: ":3306"
  mssql:
    address: ":1433"  
  
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml
  
certificatesResolvers:
  http:
    acme:
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: http