version: "3.7"
services:
  traefik:
    image: traefik:chevrotin
    container_name: traefik
    labels:
      - traefik.frontend.rule=Host:${TRAEFIK_HOSTNAME}
      - traefik.port=8080
      - traefik.enable=true
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
      - "443:443"   # TLS/SSL enable port
    networks:
      - gaming_default
      # - homeautomation_default
      - local
      - media_default
      - monitoring_default
      - webservices_default
    volumes:
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - certs:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  smtp:
    build: ./smtp
    container_name: smtp
    ports:
      - "25:25"
    networks:
      - gaming_default
      # - homeautomation_default
      - local
      - media_default
      - monitoring_default
      - webservices_default
    environment:
      - RELAY_NETWORKS= :10.0.0.0/8:172.16.0.0/12:192.168.0.0/16
      - MAILNAME=${SMTP_MAILNAME}
    restart: unless-stopped
  # mysql:

  # redis:

volumes:
  certs:
networks:
  local:
  gaming_default:
    external: true
  homeautomation_default:
    external: true
  media_default:
    external: true
  monitoring_default:
    external: true
  webservices_default:
    external: true