version: "3.7"
services:
  yopass-memcached:
    image: memcached
    container_name: yopass-memcached
    restart: unless-stopped
  yopass:
    image: jhaals/yopass
    container_name: yopass
    command: "--memcached=yopass-memcached:11211"
    networks:
      - infrastructure_local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yopass.entrypoints=http"
      - "traefik.http.routers.yopass.rule=Host(${YOPASS_HOSTNAMES})"
      - "traefik.http.routers.yopass.middlewares=https-redirect@file"
      - "traefik.http.routers.yopass-secure.entrypoints=https"
      - "traefik.http.routers.yopass-secure.rule=Host(${YOPASS_HOSTNAMES})"
      - "traefik.http.routers.yopass-secure.tls=true"
      - "traefik.http.routers.yopass-secure.tls.certresolver=http"
      - "traefik.http.routers.yopass-secure.service=yopass"
      - "traefik.http.services.yopass.loadbalancer.server.port=${YOPASS_PORT}"
    depends_on:
      - yopass-memcached
    restart: unless-stopped

  privatebin:
    image: privatebin/nginx-fpm-alpine
    container_name: privatebin
    volumes:
      - privatebindata:/srv/data
    networks:
      - infrastructure_local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.privatebin.entrypoints=http"
      - "traefik.http.routers.privatebin.rule=Host(${PRIVATEBIN_HOSTNAMES})"
      - "traefik.http.routers.privatebin.middlewares=https-redirect@file"
      - "traefik.http.routers.privatebin-secure.entrypoints=https"
      - "traefik.http.routers.privatebin-secure.rule=Host(${PRIVATEBIN_HOSTNAMES})"
      - "traefik.http.routers.privatebin-secure.tls=true"
      - "traefik.http.routers.privatebin-secure.tls.certresolver=http"
      - "traefik.http.routers.privatebin-secure.service=privatebin"
      - "traefik.http.services.privatebin.loadbalancer.server.port=${PRIVATEBIN_PORT}"
    restart: unless-stopped
    
  projectsend:
    image: linuxserver/projectsend
    container_name: projectsend
    volumes:
      - projectsenddata:/data
      - projectsendconfig:/config
    networks:
      - infrastructure_local
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - MAX_UPLOAD=${PROJECTSEND_MAXUPLOAD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.projectsend.entrypoints=http"
      - "traefik.http.routers.projectsend.rule=Host(${PROJECTSEND_HOSTNAMES})"
      - "traefik.http.routers.projectsend.middlewares=https-redirect@file"
      - "traefik.http.routers.projectsend-secure.entrypoints=https"
      - "traefik.http.routers.projectsend-secure.rule=Host(${PROJECTSEND_HOSTNAMES})"
      - "traefik.http.routers.projectsend-secure.tls=true"
      - "traefik.http.routers.projectsend-secure.tls.certresolver=http"
      - "traefik.http.routers.projectsend-secure.service=projectsend"
      - "traefik.http.services.projectsend.loadbalancer.server.port=${PROJECTSEND_PORT}"
    restart: unless-stopped

  rstudio:
    image: quantumobject/docker-rstudio:latest
    container_name: MollyRStudio
    networks:
      - infrastructure_local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rstudio.entrypoints=http"
      - "traefik.http.routers.rstudio.rule=Host(${RSTUDIO_HOSTNAMES})"
      - "traefik.http.routers.rstudio.middlewares=https-redirect@file"
      - "traefik.http.routers.rstudio-secure.entrypoints=https"
      - "traefik.http.routers.rstudio-secure.rule=Host(${RSTUDIO_HOSTNAMES})"
      - "traefik.http.routers.rstudio-secure.tls=true"
      - "traefik.http.routers.rstudio-secure.tls.certresolver=http"
      - "traefik.http.routers.rstudio-secure.service=rstudio"
      - "traefik.http.services.rstudio.loadbalancer.server.port=${RSTUDIO_PORT}"
    restart: unless-stopped    

  # codimd:

  # heimdall:

  # lychee:

  # raneto:

  # librespeed:

  # bigbluebutton:

volumes:
  privatebindata:
  projectsenddata:
  projectsendconfig:

networks:
  infrastructure_local:
    external: true