version: "3.7"
services:
  yopass-memcached:
    image: memcached
    container_name: yopass-memcached
    restart: unless-stopped
  yopass:
    image: jhaals/yopass
    container_name: yopass
    command: "--memcached=yopass-memcached:11211"
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:${TRAEFIK_HOSTNAME}
      - traefik.port=${TRAEFIK_PORT}
    restart: unless-stopped

  # heimdall:

  # lychee:

  # raneto:

  # jekyll:

# volumes:
# networks: