version: "3.7"
services:
  yopass-memcached:
    image: memcached
    container_name: yopass-memcached
    restart: unless-stopped
  yopass:
    image: jhaals/yopass
    container_name: yopass
    command: "--memcached=yopass-memcached:11211"
    networks:
      - infrastructure_local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yopass.entrypoints=http"
      - "traefik.http.routers.yopass.rule=Host(${YOPASS_HOSTNAMES})"
      - "traefik.http.routers.yopass.middlewares=https-redirect@file"
      - "traefik.http.routers.yopass-secure.entrypoints=https"
      - "traefik.http.routers.yopass-secure.rule=Host(${YOPASS_HOSTNAMES})"
      - "traefik.http.routers.yopass-secure.tls=true"
      - "traefik.http.routers.yopass-secure.tls.certresolver=http"
      - "traefik.http.routers.yopass-secure.service=yopass"
      - "traefik.http.services.yopass.loadbalancer.server.port=${YOPASS_PORT}"
    depends_on:
      - yopass-memcached
    restart: unless-stopped

  privatebin:
    image: privatebin/nginx-fpm-alpine
    container_name: privatebin
    volumes:
      - privatebindata:/srv/data
    networks:
      - infrastructure_local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.privatebin.entrypoints=http"
      - "traefik.http.routers.privatebin.rule=Host(${PRIVATEBIN_HOSTNAMES})"
      - "traefik.http.routers.privatebin.middlewares=https-redirect@file"
      - "traefik.http.routers.privatebin-secure.entrypoints=https"
      - "traefik.http.routers.privatebin-secure.rule=Host(${PRIVATEBIN_HOSTNAMES})"
      - "traefik.http.routers.privatebin-secure.tls=true"
      - "traefik.http.routers.privatebin-secure.tls.certresolver=http"
      - "traefik.http.routers.privatebin-secure.service=privatebin"
      - "traefik.http.services.privatebin.loadbalancer.server.port=${PRIVATEBIN_PORT}"
    restart: unless-stopped
    
  # projectsend:

  # rstudio:

  # codimd:

  # heimdall:

  # lychee:

  # raneto:

  # librespeed:

  # bigbluebutton:

volumes:
  privatebindata:

networks:
  infrastructure_local:
    external: true